project:
  type: website

website:
  title: "CBRC-SPEC Tutorials"
  navbar:
    background: "#013c58"
    pinned: true
    search: false
    left:
      - text: Tutorials
        menu:
          - href: 10x.qmd
            text: 10x Genomics Chromium
          - href: parse.qmd
            text: Parse Evercode WT
          - href: seqfish_pipeline.Rmd
            text: seqFISH
      - text: seqspec
        menu:
          - href: seqspec.qmd
            text: What is seqspec?
          - href: seqspec_tutorials.qmd
            text: Tutorials
      - href: kb_python.qmd
        text: kb-python
      - text: Workflows
        menu:
          - href: sample_pipeline.ipynb
            text: An Example scRNA-seq Pipeline
          - text: "---"
          - href: seqfish_pipeline.Rmd
            text: An Example Spatial Transcriptomics Pipeline
      - text: Installation
        menu:
          - href: conda.qmd
            text: Creating a Conda Environment
          - href: python_packages.qmd
            text: Installing Python Packages
          - href: R_packages.qmd
            text: Installing R Packages

      - href: contact_us.qmd
        text: Contact Us
  page-footer:
    left: 
      <img src="black_Caltech_logo.png" alt="Caltech Logo" width="300">
    background: "	#ff8c00"
format:
  html:
    theme:
      light: flatly
    css: styles.css
    toc: true
    mainfont: "Inter"
    fontsize: 1rem
    linestretch: 1.6
    highlight-style: ayu-dark
    toc-location: left


